apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAogICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImJIVnJlV0Z1YjNaaGJuUnZiakV6TVRwbmFIQmZZbll5UW1wSVYyOHdVM2RyV2xWTlprcDZjRWxGVldGSVRHcG9OMEp0TW5wNGMyWngiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
